// -*- c++ -*-
#ifndef _GSTREAMERMM_WRAP_INIT_H
#define _GSTREAMERMM_WRAP_INIT_H

// wrap_init.cc is generated by tools/generate_wrap_init.pl

#include <glibmm.h>

namespace Gst
{
  void wrap_init();
}

#endif //_GSTREAMERMM_WRAP_INIT_H


