// -*- c++ -*-
#ifndef _GSTMM_GST_WRAP_INIT_H
#define _GSTMM_GST_WRAP_INIT_H

// gst_wrap_init.cc is generated by tools/generate_gst_wrap_init.pl

#include <glibmm.h>

namespace Gst
{
  void gst_wrap_init();
}

#endif //_GSTMM_GST_WRAP_INIT_H


