/* gstreamerbase/gstreamerbasemmconfig.h.  Generated from gstreamerbasemmconfig.h.in by configure.  */
#ifndef _GSTREAMERBASEMM_CONFIG_H
#define _GSTREAMERBASEMM_CONFIG_H 1

/* version numbers */
/* #undef GSTREAMERBASEMM_MAJOR_VERSION */
/* #undef GSTREAMERBASEMM_MINOR_VERSION */
/* #undef GSTREAMERBASEMM_MICRO_VERSION */

// detect common platforms
#if defined(_WIN32)
// Win32 compilers have a lot of varation
#if defined(_MSC_VER)
#define GSTREAMERBASEMM_MSC
#define GSTREAMERBASEMM_WIN32
#define GSTREAMERBASEMM_DLL
#elif defined(__CYGWIN__)
#define GSTREAMERBASEMM_CONFIGURE
#elif defined(__MINGW32__)
#define GSTREAMERBASEMM_WIN32
#define GSTREAMERBASEMM_CONFIGURE
#else
//AIX clR compiler complains about this even though it doesn't get this far:
//#warning "Unknown architecture (send me gcc --dumpspecs or equiv)"
#endif
#else
#define GSTREAMERBASEMM_CONFIGURE
#endif /* _WIN32 */

#ifdef GSTREAMERBASEMM_CONFIGURE
/* compiler feature tests that are used during compile time and run-time
   by gtk-- only. tests used by gdk-- and gtk-- should go into
   gdk--config.h.in */
/* #undef GSTREAMERBASEMM_CXX_HAVE_MUTABLE */
/* #undef GSTREAMERBASEMM_CXX_HAVE_NAMESPACES */
//#undef GSTREAMERBASEMM_CXX_GAUB
//#undef GSTREAMERBASEMM_CXX_AMBIGUOUS_TEMPLATES
/* #undef GSTREAMERBASEMM_HAVE_NAMESPACE_STD */
/* #undef GSTREAMERBASEMM_HAVE_STD_ITERATOR_TRAITS */
/* #undef GSTREAMERBASEMM_HAVE_SUN_REVERSE_ITERATOR */
/* #undef GSTREAMERBASEMM_HAVE_TEMPLATE_SEQUENCE_CTORS */
/* #undef GSTREAMERBASEMM_HAVE_DISAMBIGUOUS_CONST_TEMPLATE_SPECIALIZATIONS */
/* #undef GSTREAMERBASEMM_COMPILER_SUN_FORTE */
/* #undef GSTREAMERBASEMM_DEBUG_REFCOUNTING */
/* #undef GSTREAMERBASEMM_CAN_USE_DYNAMIC_CAST_IN_UNUSED_TEMPLATE_WITHOUT_DEFINITION */
/* #undef GSTREAMERBASEMM_CAN_ASSIGN_NON_EXTERN_C_FUNCTIONS_TO_EXTERN_C_CALLBACKS */
/* #undef GSTREAMERBASEMM_CAN_USE_NAMESPACES_INSIDE_EXTERNC */
/* #undef GSTREAMERBASEMM_HAVE_ALLOWS_STATIC_INLINE_NPOS */
#endif

#ifdef GSTREAMERBASEMM_MSC
  #define GSTREAMERBASEMM_CXX_HAVE_MUTABLE 1
  #define GSTREAMERBASEMM_CXX_HAVE_NAMESPACES 1
  #define GSTREAMERBASEMM_HAVE_NAMESPACE_STD 1
  #define GSTREAMERBASEMM_HAVE_STD_ITERATOR_TRAITS 1
  #define GSTREAMERBASEMM_HAVE_TEMPLATE_SEQUENCE_CTORS 2
  #define GSTREAMERBASEMM_HAVE_DISAMBIGUOUS_CONST_TEMPLATE_SPECIALIZATIONS 1
  #define GSTREAMERBASEMM_CAN_USE_DYNAMIC_CAST_IN_UNUSED_TEMPLATE_WITHOUT_DEFINITION 1
  #define GSTREAMERBASEMM_CAN_ASSIGN_NON_EXTERN_C_FUNCTIONS_TO_EXTERN_C_CALLBACKS 1
  #define GSTREAMERBASEMM_CAN_USE_NAMESPACES_INSIDE_EXTERNC 1
  #pragma warning (disable: 4786 4355 4800 4181)
#endif

#ifndef GSTREAMERBASEMM_HAVE_NAMESPACE_STD
#  define GSTREAMERBASEMM_USING_STD(Symbol) namespace std { using ::Symbol; }
#else
#  define GSTREAMERBASEMM_USING_STD(Symbol) /* empty */
#endif

#ifdef GSTREAMERBASEMM_DLL
  #if defined(GSTREAMERBASEMM_BUILD) && defined(_WINDLL)
    /* Do not dllexport as it is handled by gendef on MSVC */
    #define GSTREAMERBASEMM_API 
  #elif !defined(GSTREAMERBASEMM_BUILD)
    #define GSTREAMERBASEMM_API __declspec(dllimport)
  #else
    /* Build a static library */
    #define GSTREAMERBASEMM_API
  #endif /* GSTREAMERBASEMM_BUILD - _WINDLL */
#else
  #define GSTREAMERBASEMM_API
#endif /* GSTREAMERBASEMM_DLL */

#endif /* _GSTREAMERBASEMM_CONFIG_H */

